# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEditValue = QtWidgets.QLineEdit(Dialog)
        self.lineEditValue.setGeometry(QtCore.QRect(12, 16, 371, 31))
        self.lineEditValue.setObjectName("lineEditValue")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(9, 53, 381, 241))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton1_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_11.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_11.setAutoDefault(False)
        self.pushButton1_11.setObjectName("pushButton1_11")
        self.gridLayout.addWidget(self.pushButton1_11, 0, 1, 1, 1)
        self.pushButton1_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_9.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_9.setAutoDefault(False)
        self.pushButton1_9.setObjectName("pushButton1_9")
        self.gridLayout.addWidget(self.pushButton1_9, 1, 0, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(self.widget)
        self.pushButton2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton2.setAutoDefault(False)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 2, 1, 1, 1)
        self.pushButton1_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_7.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_7.setAutoDefault(False)
        self.pushButton1_7.setObjectName("pushButton1_7")
        self.gridLayout.addWidget(self.pushButton1_7, 1, 2, 1, 1)
        self.pushButtonSoma = QtWidgets.QPushButton(self.widget)
        self.pushButtonSoma.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButtonSoma.setAutoDefault(False)
        self.pushButtonSoma.setObjectName("pushButtonSoma")
        self.gridLayout.addWidget(self.pushButtonSoma, 2, 3, 1, 1)
        self.pushButton1_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_4.setAutoDefault(False)
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.gridLayout.addWidget(self.pushButton1_4, 2, 2, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(self.widget)
        self.pushButton1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1.setAutoDefault(False)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 2, 0, 1, 1)
        self.pushButton1_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_6.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_6.setAutoDefault(False)
        self.pushButton1_6.setObjectName("pushButton1_6")
        self.gridLayout.addWidget(self.pushButton1_6, 1, 3, 1, 1)
        self.pushButton0_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton0_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton0_2.setAutoDefault(False)
        self.pushButton0_2.setFlat(False)
        self.pushButton0_2.setObjectName("pushButton0_2")
        self.gridLayout.addWidget(self.pushButton0_2, 3, 1, 1, 1)
        self.pushButton0 = QtWidgets.QPushButton(self.widget)
        self.pushButton0.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton0.setAutoDefault(False)
        self.pushButton0.setFlat(False)
        self.pushButton0.setObjectName("pushButton0")
        self.gridLayout.addWidget(self.pushButton0, 3, 0, 1, 1)
        self.pushButton1_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_2.setAutoDefault(False)
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.gridLayout.addWidget(self.pushButton1_2, 3, 2, 1, 1)
        self.pushButton1_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_13.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_13.setAutoDefault(False)
        self.pushButton1_13.setObjectName("pushButton1_13")
        self.gridLayout.addWidget(self.pushButton1_13, 0, 3, 1, 1)
        self.pushButton1_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_12.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_12.setAutoDefault(False)
        self.pushButton1_12.setObjectName("pushButton1_12")
        self.gridLayout.addWidget(self.pushButton1_12, 0, 2, 1, 1)
        self.pushButton1_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_8.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_8.setAutoDefault(False)
        self.pushButton1_8.setObjectName("pushButton1_8")
        self.gridLayout.addWidget(self.pushButton1_8, 1, 1, 1, 1)
        self.pushButton1_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton1_10.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton1_10.setAutoDefault(False)
        self.pushButton1_10.setObjectName("pushButton1_10")
        self.gridLayout.addWidget(self.pushButton1_10, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton1.clicked.connect(self.lineEditValue.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculadora"))
        self.pushButton1_11.setText(_translate("Dialog", "1"))
        self.pushButton1_9.setText(_translate("Dialog", "1"))
        self.pushButton2.setText(_translate("Dialog", "1"))
        self.pushButton1_7.setText(_translate("Dialog", "1"))
        self.pushButtonSoma.setText(_translate("Dialog", "+"))
        self.pushButton1_4.setText(_translate("Dialog", "1"))
        self.pushButton1.setText(_translate("Dialog", "1"))
        self.pushButton1_6.setText(_translate("Dialog", "1"))
        self.pushButton0_2.setText(_translate("Dialog", "0"))
        self.pushButton0.setText(_translate("Dialog", "0"))
        self.pushButton1_2.setText(_translate("Dialog", "1"))
        self.pushButton1_13.setText(_translate("Dialog", "1"))
        self.pushButton1_12.setText(_translate("Dialog", "1"))
        self.pushButton1_8.setText(_translate("Dialog", "1"))
        self.pushButton1_10.setText(_translate("Dialog", "1"))

